variable "rg-name" {}
variable "location" {}
variable "environment" {}
variable "owner" {}
variable "vnet_name" {}
variable "vnet_cidr" {}
variable "subnet1_cidr" {}
variable "subnet2_cidr" {}
variable "subnet3_cidr" {}
variable "subnet1_name" {}
variable "subnet2_name" {}
variable "subnet3_name" {}
variable "allowed_ip" {}
